void main() {
    print (tid(), " === START ===");
    object o1 = alloc(1000,0);
    int i = 0;
    while (i<500) {
    	o1.object[0] = alloc(0,1000);
    	i = i + 1;
    }
    print(tid(), " === Done with small objects ===");
    object o2 = alloc(0,700000);
    print (tid(), " === END ==="); 
}

/*
void main() {
  int cycles = 300;
  int cycleSize = 100;

  int i = 1;
  while (i < cycles) {
    createCycle(cycleSize);
    i = i + 1;
  }
}

object createCycle(int size) {
  object head = alloc(1, 10);
  object tail = head;
  while(size > 0) {
    tail.object[0] = alloc(1, 10);
    tail = tail.object[0];
    size = size - 1;
  }
  tail.object[0] = head;
  return head;
}
*/